### ISSUE TITLE
CNAME Support

### ISSUE THREAD

**Issue by RaannaKasturi** [r5d/acmens#5]
Hello. I've forked this repo and has been trying to integrate Cloudflare and other DNS Services into this and also building the python library.
Moreover, I'm also trying to use cname domain aliases to make the SSL certificates issuing on the hosts that do not support TXT records editing.
It would be of a great help if you can help me out.

Thankyou.

Here's my github repo: [https://github.com/RaannaKasturi/getSSL](https://github.com/RaannaKasturi/getSSL)

**Comment by r5d** [comment]
@RaannaKasturi 

If you're unable to add TXT records for a DNS domain name, use the
http challenge instead of the dns challenge.

For the http challenge you will be requested to the add a file to
serve (via http) from the DNS domain name for which you're trying to get a ssl
certificate.

acmens defaults to the http challenge type if you do not pass the
`--challenge` option.

**Comment by RaannaKasturi** [comment]
Nevermind, I've found a workaround to use CNAME instead of TXT Records
